# Generated by Django 5.2.8 on 2025-12-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_remove_post_date_posted_post_data_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Optional: YouTube video URL', null=True),
        ),
    ]
